### ISSUE TITLE
Little padding below .selectize-control

### ISSUE THREAD

**Issue by joelcuevas** [herschel666/selectize-scss#10]
For some reason the property `height: auto` in `.selectize-control` adds some little "visual padding" (not css padding) below the control despite anything I do.  If I delete this property (it cannot be override) everything (including tags) works fine and the padding is gone.

![image](https://cloud.githubusercontent.com/assets/275014/18220251/af7e7cda-7135-11e6-9145-1d3443b361b7.png)
Could it be possible to remove it? Do you think it could break something?

The rule is at `selectize-scss/src/selectize.bootstrap3.scss` line 67.

**Comment by flakeparadigm** [comment]
Hi @joelcuevas 

I believe the intention of this repository is to create an _exact copy_ of the selectize stylesheets, just translated from less to scss. This change would cause a difference between this repo and the original selectize styles.

If you can reproduce the issue with the original selectize files, perhaps it would be worth reporting to them if this extra padding causes you an issue.

Selectize.js repo link for quick access: https://github.com/selectize/selectize.js

**Comment by herschel666** [comment]
@joelcuevas Please open an issue in the [selectize.js-repo](https://github.com/selectize/selectize.js/issues).
